# Generated by Django 3.2.11 on 2022-06-06 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_product_description'),
        ('mainapp', '0002_auto_20220523_2206'),
    ]

    operations = [
    ]
