# Generated by Django 3.2.11 on 2022-07-24 15:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_auto_20220724_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 26, 15, 23, 10, 315294, tzinfo=utc)),
        ),
    ]