# Generated by Django 3.2.11 on 2022-07-24 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CANCELED', 'Canceled'), ('PAID', 'Paid'), ('DELIVERED', 'Delivered'), ('CREATED', 'Created'), ('SENT', 'Sent')], default='CREATED', max_length=16),
        ),
    ]
